name: Deploy to Server

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MYSECRETKEY1 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 3.7.69.51 >> ~/.ssh/known_hosts
        env:
          MYSECRETKEY1: ${{ secrets.MYSECRETKEY1 }}

      - name: Install Dependencies and Build
        run: |
          # Install dependencies and build your React app
          npm ci
          npm run build

      - name: Deploy Build to Server
        run: |
          # Copy the build artifacts to the server using SCP
          scp -r ./build/* ubuntu@3.7.69.51:/home/ubuntu/projects
